services:
  app:
    image: ghcr.io/k2works/ai-programing-exercise/core:0.1.0
    volumes:
      - ./:/srv/app
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    command: bash
    tty: true
    stdin_open: true

  mkdocs:
    build:
      context: .
      dockerfile: ./docs/Dockerfile
    environment:
        PLANTUML_SERVER_URL: http://plantuml:8080/plantuml
    volumes:
      - ./docs:/docs/docs
      - ./README.md:/docs/README.md
      - ./mkdocs.yml:/docs/mkdocs.yml
      - ./site:/docs/site
    ports:
      - "8000:8000"
    command: mkdocs serve --dev-addr=0.0.0.0:8000
    links:
      - plantuml

  plantuml:
    image: plantuml/plantuml-server:jetty
    environment:
      BASE_URL: plantuml

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mrs
      POSTGRES_USER: mrs_user
      POSTGRES_PASSWORD: mrs_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/backend/mrs/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: >
      postgres -c log_statement=all 
               -c log_destination=stderr 
               -c log_min_messages=info

volumes:
  postgres_data:
