services:
  app:
    image: ghcr.io/k2works/ai-programing-exercise/ai-programing-exercise:0.0.1
    volumes:
      - ./:/srv
    command: bash
    tty: true
    stdin_open: true

  mkdocs:
    build:
      context: .
      dockerfile: ./docs/Dockerfile
    environment:
        PLANTUML_SERVER_URL: http://plantuml:8080/plantuml
    volumes:
      - ./docs:/docs/docs
      - ./README.md:/docs/README.md
      - ./mkdocs.yml:/docs/mkdocs.yml
      - ./site:/docs/site
    ports:
      - "8000:8000"
    command: mkdocs serve --dev-addr=0.0.0.0:8000
    links:
      - plantuml

  plantuml:
    image: plantuml/plantuml-server:jetty
    environment:
      BASE_URL: plantuml
