-- HLint configuration file for complexity analysis
-- このファイルでHLintのカスタムルールを定義します

-- 循環複雑度に関する警告
{-# OPTIONS_GHC -Wno-missing-signatures #-}

-- 複雑な関数に対する警告
warn = {lhs = "f", rhs = "g", note = "Consider simplifying this function"}

-- ネストが深い場合の警告
warn = {lhs = "if a then if b then c else d else e", 
        rhs = "case (a, b) of (True, True) -> c; (True, False) -> d; _ -> e",
        note = "Consider using case expressions for multiple conditions"}

-- 長いガードの警告
warn = {lhs = "f x | condition1 = result1 | condition2 = result2 | condition3 = result3 | otherwise = result4",
        note = "Consider breaking down complex guard conditions"}

-- パターンマッチングの複雑さ
warn = {note = "Consider simplifying complex pattern matching"}

-- モナドの複雑なチェーン
warn = {lhs = "do a; b; c; d; e; f; g; h",
        note = "Consider breaking down long monadic chains"}
