# HLint configuration file
# HLintの設定ファイル

# 無視する警告
- ignore: {name: "Use camelCase"}
- ignore: {name: "Redundant bracket"}

# 推奨事項
- suggest: {lhs: "concat (map f xs)", rhs: "concatMap f xs"}
- suggest: {lhs: "foldr (++) []", rhs: "concat"}

# 警告
- warn: {lhs: "length xs == 0", rhs: "null xs", note: "Use null to test for empty"}
- warn: {lhs: "x ++ []", rhs: "x", note: "Redundant append"}

# エラー
- error: {lhs: "map f (map g xs)", rhs: "map (f . g) xs", note: "Use composition"}
