import { Job } from '@/features/jobs';

export const mockJobs: Job[] = [
  {
    id: '1',
    organizationId: 'org-1',
    position: 'Senior Frontend Developer',
    department: 'Engineering',
    location: 'Remote',
    info: 'We are looking for a skilled Senior Frontend Developer to join our engineering team. You will be responsible for building user-facing features using modern web technologies.',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    organizationId: 'org-1',
    position: 'Product Manager',
    department: 'Product',
    location: 'Tokyo',
    info: 'Seeking an experienced Product Manager to drive product strategy and roadmap. You will work closely with engineering, design, and business teams.',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: '3',
    organizationId: 'org-1',
    position: 'UX Designer',
    department: 'Design',
    location: 'San Francisco',
    info: 'Looking for a creative UX Designer to help create intuitive and beautiful user experiences. Experience with design systems preferred.',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: '4',
    organizationId: 'org-1',
    position: 'Backend Engineer',
    department: 'Engineering',
    location: 'Berlin',
    info: 'Join our backend team to build scalable and reliable systems. Experience with microservices architecture and cloud platforms required.',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-07'),
  },
  {
    id: '5',
    organizationId: 'org-1',
    position: 'Data Scientist',
    department: 'Data',
    location: 'Remote',
    info: 'We need a Data Scientist to analyze user behavior and improve our products through data-driven insights. Machine learning experience is a plus.',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-03'),
  },
];