-- ユーザーテーブル
CREATE TABLE usr (
    user_id    VARCHAR(255) NOT NULL PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role_name  VARCHAR(255) NOT NULL
);

-- 会議室テーブル
CREATE TABLE meeting_room (
    room_id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    room_name VARCHAR(255) NOT NULL
);

-- 予約可能会議室テーブル
CREATE TABLE reservable_room (
    reserved_date DATE NOT NULL,
    room_id       INT NOT NULL,
    PRIMARY KEY (reserved_date, room_id),
    FOREIGN KEY (room_id) REFERENCES meeting_room(room_id)
);

-- 予約テーブル
CREATE TABLE reservation (
    reservation_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    start_time     TIME NOT NULL,
    end_time       TIME NOT NULL,
    reserved_date  DATE NOT NULL,
    room_id        INT NOT NULL,
    user_id        VARCHAR(255) NOT NULL,
    FOREIGN KEY (reserved_date, room_id) REFERENCES reservable_room(reserved_date, room_id),
    FOREIGN KEY (user_id) REFERENCES usr(user_id)
);
